version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats-jetstream-server
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management port
      - "6222:6222"  # Cluster connections
    command: [
      "--jetstream",
      "--store_dir=/data",
      "--http_port=8222",
      "--port=4222",
      "--max_memory_store=1GB",
      "--max_file_store=10GB",
      "--cluster_name=jetstream-cluster",
      "--cluster=nats://0.0.0.0:6222",
      "--log_file=/data/nats-server.log",
      "--debug=false",
      "--trace=false"
    ]
    volumes:
      - nats_jetstream_data:/data
    environment:
      - NATS_SERVER_NAME=nats-jetstream-local
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  nats_jetstream_data:
    driver: local