services:
  events-audit:
    image: events-audit:binary
    container_name: events-audit-app
    ports:
      - "8080:8080"
    environment:
      - AUDIT_LISTNER_AUDIT=nats
      - AUDIT_LISTNER_AUDIT_NATS_ADDR=nats://nats:4222
      - AUDIT_LISTNER_LOG_LEVEL=info
      - AUDIT_LISTNER_LOG_FORMAT=json
      - AUDIT_LISTNER_AUDIT_TOPIC=accountats
      - AUDIT_LISTNER_AUDIT_STREAM_NAME=EVENTS
      - AUDIT_LISTNER_AUDIT_CONSUMER_NAME=events-audit-durable
      - AUDIT_LISTNER_AUDIT_DURABLE_NAME=events-audit-durable
      - AUDIT_LISTNER_AUDIT_CREATE_STREAM=true
    depends_on:
      nats:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nats:
    image: nats:2.10-alpine
    container_name: nats-jetstream-server
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management port
    command: [
      "--jetstream",
      "--store_dir=/data",
      "--http_port=8222",
      "--port=4222"
    ]
    volumes:
      - nats_jetstream_data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  nats_jetstream_data:
    driver: local